name: My first workflow test
on: [push]
jobs:
 Test-github-actions-version_check:
  runs-on: ubuntu-latest
  steps:
   - name: Check python and docker version
     uses: actions/checkout@v3
   - run: python --version
   - run: docker --version

 Test-github-actions-pylint_check:
  runs-on: ubuntu-latest
  steps:
   - name: Check python consistency in app.py
     uses: actions/setup-python@v2
   - run: sudo apt install pylint
   - run: find . -name '*.py' -exec pylint {} \;

 Test-github-actions-docker_image:
  runs-on: ubuntu-latest
  steps:
   - name: Create docker image
     uses: actions/checkout@v3
   - run: docker build --tag test-flask-app .
