name: My first workflow test
on: [push]
jobs:
 Test-github-actions:
  runs-on: ubuntu-latest
  steps:
   - run: docker --version 
   - name: Check docker version
     uses: actions/checkout@v3
#jobs:
 Test-github-actions:
  runs-on: ubuntu-latest
  steps:
   - run: python --version
   - run: docker --version
   - name: Check python and docker version
     uses: actions/checkout@v3
#jobs:
 Test-github-actions:
  runs-on: ubuntu-latest
  steps:
   - run: pylint app.py
   - name: Check python consistency in app.py
     uses: actions/checkout@v3
#jobs:
 Test-github-actions:
  runs-on: ubuntu-latest
  steps:
   - run: echo "OKEJ!!"
   - name: Check python consistency in app.py
     uses: actions/checkout@v3
